# Site settings
title: Max Rogers
email: MR@maxrogers.me
description: "Edit description in _config.yml"
info: "Racine, Wisconsin"
message: "iOS Developer"
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.maxrogers.me" # the base hostname & protocol for your site
twitter_username:
# Build settings
markdown: kramdown
author:
    name: Max Rogers
    twitter:
    url: http://www.maxrogers.me
    header_bg: /images/profileheader.png
    avatar: /images/headshot.png
    email: MR@maxrogers.me
facebook:
    image: /images/delightfuldev-facebook-cover.png
